inference_only: true

inference_data_path: "data/test.json"
text_field: "text"
inference_output_path: "predictions/GLiNEREntityRecognizer/glinerMulti_finetuned"
#eval_data_path: "data/test.json"

model_name: "urchade/gliner_multi-v2.1"
model_path: "checkpoints/GLiNEREntityRecognizer/glinerMulti_edil"

threshold: 0.5
batch_size: 8
max_len: 512
seed: 42
