inference_only: true

inference_data_path: "data/test.json"
text_field: "text"
inference_output_path: "predictions/GLiNEREntityRecognizer/SauerkrautLM_zero_shot"
#eval_data_path: "data/test.json"

model_name: "VAGOsolutions/SauerkrautLM-GLiNER"
model_path: null

threshold: 0.5
batch_size: 8
max_len: 512
seed: 42
