provider: "ollama"
model: "gemma3:27b"
api_key: null
base_url: null
azure_endpoint: null
azure_api_version: "2024-02-01"

inference_data_path: "data/test.json"
text_field: "text"
inference_output_path: "predictions/LLMEntityRecognizer/raw"
language: "IT"
#checkpoint_path: "checkpoints/LLMEntityRecognizer/ollama_entity_recognition_gemma-3-27b-it-fewshot-semantic.jsonl"

prompts_path: "src/entityRecognizer/prompts_IT.json"
system_prompt_key: "base"
user_prompt_key: "base"
system_as_user: false

temperature: 0.2
max_new_tokens: 2048
device: null
raw: false

few_shot:
  k: 4
  strategy: "semantic"
  examples_path: "data/training.json"
  text_field: "text"
  #embedding_model: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  embedding_model: "nickprock/sentence-bert-base-italian-uncased"
  embeddings_cache_path: "cache/LLMEntityRecognizer/training_semantic_embeddings"
  embedding_device: null
  exclude_same_text: true